language: android

sudo: required

android:
  components:
    - platform-tools
    - tools

    # the BuildTools version used by your project
    - build-tools-24.0.2
    - build-tools-25.0.1

    # the SDK version used to compile your project
    - android-24
    - android-25

    # additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # specify system image for instrumentation tests
    - sys-img-armeabi-v7a-android-21

jdk:
  - oraclejdk8

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=25
    - GRADLE_OPTS="-Xms128m"
    - MALLOC_ARENA_MAX=2

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
